### PR TITLE
Fix #680 and Add category ladders

### LINKED ISSUE #680: Using `Set 'Downloaded' status automatically` does not always work
**Describe the bug**
I thought I had seen this issue when updating, so just now tested to be sure.  When no books are listed as downloads, and you use the `Set 'Downloaded' status automatically...` option, sometimes it appears to do nothing.

**To Reproduce**

1. Have all your books in your library, and in your folder
2. Delete all your files (into your Recycle Bin)
3. Use `Set 'Downloaded' status automatically...` - All the library items go to "Red" as they should
4. Restore the files from the Recycle Bin.
5. Use `Set 'Downloaded' status automatically...` - All the library items are still "Red"

I believe I actually closed Libation and restarted it at each step in this also.  Not sure if that made a difference in the results or not.  I believe I also manually marked PDF files as not download.

**Expected behavior**
All your items should go "Green" after you restore the files and scan for existing files.

**Screenshots**

**Platform**

Windows 11, Libation 10.6.2 Chardonnay

**Log Files**
2023-07-16 12:15:46.540 -05:00 [INF] (at AppScaffolding.LibationScaffolding.logStartupState(LibationFileManager.Configuration)) 

 {}2023-07-16 12:15:46.573 -05:00 [INF] (at AppScaffolding.LibationScaffolding.logStartupState(LibationFileManager.Configuration)) Begin. {"AppName":"Libation","Version":"10.6.2.1","ReleaseIdentifier":"WindowsAvalonia","OS":"Windows","InteropFunctionsType":"WindowsConfigApp.WinInterop","Mode":"Release","LogLevel_Verbose_Enabled":false,"LogLevel_Debug_Enabled":false,"LogLevel_Information_Enabled":true,"LogLevel_Warning_Enabled":true,"LogLevel_Error_Enabled":true,"LogLevel_Fatal_Enabled":true,"BetaOptIn":false,"UseCoverAsFolderIcon":true,"LibationFiles":"C:\\Users\\CLHat\\Libation","BooksDirectory":"\\\\?\\C:\\Users\\CLHat\\Documents\\Libation\\Books","InProgress":"C:\\Users\\CLHat\\AppData\\Local\\Temp\\Libation","DownloadsInProgressDirectory":"\\\\?\\C:\\Users\\CLHat\\AppData\\Local\\Temp\\Libation\\DownloadsInProgress","DownloadsInProgressFiles":0,"DecryptInProgressDirectory":"\\\\?\\C:\\Users\\CLHat\\AppData\\Local\\Temp\\Libation\\DecryptInProgress","DecryptInProgressFiles":0}
 {}2023-07-16 12:15:46.689 -05:00 [ERR] (at LibationFileManager.InteropFactory.CurrentDomain_AssemblyResolve(System.Object, System.ResolveEventArgs)) Unable to load module Windows, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime
 {}2023-07-16 12:15:46.707 -05:00 [ERR] (at LibationFileManager.InteropFactory.CurrentDomain_AssemblyResolve(System.Object, System.ResolveEventArgs)) Unable to load module Microsoft.Windows.SDK.NET, Culture=neutral, PublicKeyToken=null
 {}2023-07-16 12:15:47.216 -05:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"total":37,"booksFullyBackedUp":37,"booksDownloadedOnly":0,"booksNoProgress":0,"booksError":0,"booksUnavailable":0}
 {}2023-07-16 12:15:47.230 -05:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"total":4,"pdfsDownloaded":4,"pdfsNotDownloaded":0,"pdfsUnavailable":0}
 {}2023-07-16 12:15:47.680 -05:00 [INF] (at AudibleUtilities.ApiExtended+<CreateAsync>d__7.MoveNext()) {"LoginType":"ILoginChoiceEager","Account":"AccountId=C[...]h@g[...]l.c[...]m|AccountName=C[...]s|Locale=us","LocaleName":"us"}
 {}2023-07-16 12:15:47.720 -05:00 [INF] (at ApplicationServices.LibraryCommands+<scanAccountAsync>d__18.MoveNext()) ImportLibraryAsync. {"Account":"AccountId=C[...]h@g[...]l.c[...]m|AccountName=C[...]s|Locale=us"}
 {}2023-07-16 12:15:47.764 -05:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"total":37,"booksFullyBackedUp":37,"booksDownloadedOnly":0,"booksNoProgress":0,"booksError":0,"booksUnavailable":0}
 {}2023-07-16 12:15:47.790 -05:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"total":4,"pdfsDownloaded":4,"pdfsNotDownloaded":0,"pdfsUnavailable":0}
 {}2023-07-16 12:15:49.270 -05:00 [INF] (at AudibleApi.Api+<downloadItemPage>d__48.MoveNext()) Page 1: 37 results
 {}2023-07-16 12:15:49.287 -05:00 [INF] (at AudibleUtilities.ApiExtended+<getItemsAsync>d__14.MoveNext()) Completed indexing series episodes after 0 ms.
 {}2023-07-16 12:15:49.297 -05:00 [INF] (at AudibleUtilities.ApiExtended+<getItemsAsync>d__14.MoveNext()) Completed library scan in 1547 ms.
 {}2023-07-16 12:15:49.317 -05:00 [INF] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__15.MoveNext()) GetAllLibraryItems: Total count 37
 {}2023-07-16 12:15:49.329 -05:00 [INF] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__15.MoveNext()) Begin long-running import
 {}2023-07-16 12:15:49.451 -05:00 [INF] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__15.MoveNext()) Import complete. New count 0
 {}2023-07-16 12:16:02.141 -05:00 [INF] (at FileManager.PersistentDictionary.writeFile(System.String, Newtonsoft.Json.Linq.JToken)) Config changed. {"propertyName":"MessageBoxWindow","newValue":"{\r\n  \"X\": 707,\r\n  \"Y\": 418,\r\n  \"Height\": 109,\r\n  \"Width\": 401,\r\n  \"IsMaximized\": false\r\n}"}
 {}2023-07-16 12:16:02.326 -05:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"total":37,"booksFullyBackedUp":0,"booksDownloadedOnly":0,"booksNoProgress":37,"booksError":0,"booksUnavailable":0}
 {}2023-07-16 12:16:02.328 -05:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"total":37,"booksFullyBackedUp":0,"booksDownloadedOnly":0,"booksNoProgress":37,"booksError":0,"booksUnavailable":0}
 {}2023-07-16 12:16:02.339 -05:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"total":4,"pdfsDownloaded":4,"pdfsNotDownloaded":0,"pdfsUnavailable":0}
 {}2023-07-16 12:16:02.349 -05:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"total":4,"pdfsDownloaded":4,"pdfsNotDownloaded":0,"pdfsUnavailable":0}
 {}2023-07-16 12:16:23.609 -05:00 [INF] (at AppScaffolding.LibationScaffolding.logStartupState(LibationFileManager.Configuration)) 

 {}2023-07-16 12:16:23.654 -05:00 [INF] (at AppScaffolding.LibationScaffolding.logStartupState(LibationFileManager.Configuration)) Begin. {"AppName":"Libation","Version":"10.6.2.1","ReleaseIdentifier":"WindowsAvalonia","OS":"Windows","InteropFunctionsType":"WindowsConfigApp.WinInterop","Mode":"Release","LogLevel_Verbose_Enabled":false,"LogLevel_Debug_Enabled":false,"LogLevel_Information_Enabled":true,"LogLevel_Warning_Enabled":true,"LogLevel_Error_Enabled":true,"LogLevel_Fatal_Enabled":true,"BetaOptIn":false,"UseCoverAsFolderIcon":true,"LibationFiles":"C:\\Users\\CLHat\\Libation","BooksDirectory":"\\\\?\\C:\\Users\\CLHat\\Documents\\Libation\\Books","InProgress":"C:\\Users\\CLHat\\AppData\\Local\\Temp\\Libation","DownloadsInProgressDirectory":"\\\\?\\C:\\Users\\CLHat\\AppData\\Local\\Temp\\Libation\\DownloadsInProgress","DownloadsInProgressFiles":0,"DecryptInProgressDirectory":"\\\\?\\C:\\Users\\CLHat\\AppData\\Local\\Temp\\Libation\\DecryptInProgress","DecryptInProgressFiles":0}
 {}2023-07-16 12:16:23.773 -05:00 [ERR] (at LibationFileManager.InteropFactory.CurrentDomain_AssemblyResolve(System.Object, System.ResolveEventArgs)) Unable to load module Windows, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime
 {}2023-07-16 12:16:23.791 -05:00 [ERR] (at LibationFileManager.InteropFactory.CurrentDomain_AssemblyResolve(System.Object, System.ResolveEventArgs)) Unable to load module Microsoft.Windows.SDK.NET, Culture=neutral, PublicKeyToken=null
 {}2023-07-16 12:16:24.353 -05:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"total":37,"booksFullyBackedUp":0,"booksDownloadedOnly":0,"booksNoProgress":37,"booksError":0,"booksUnavailable":0}
 {}2023-07-16 12:16:24.380 -05:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"total":4,"pdfsDownloaded":4,"pdfsNotDownloaded":0,"pdfsUnavailable":0}
 {}2023-07-16 12:16:24.758 -05:00 [INF] (at AudibleUtilities.ApiExtended+<CreateAsync>d__7.MoveNext()) {"LoginType":"ILoginChoiceEager","Account":"AccountId=C[...]h@g[...]l.c[...]m|AccountName=C[...]s|Locale=us","LocaleName":"us"}
 {}2023-07-16 12:16:24.796 -05:00 [INF] (at ApplicationServices.LibraryCommands+<scanAccountAsync>d__18.MoveNext()) ImportLibraryAsync. {"Account":"AccountId=C[...]h@g[...]l.c[...]m|AccountName=C[...]s|Locale=us"}
 {}2023-07-16 12:16:24.859 -05:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"total":37,"booksFullyBackedUp":0,"booksDownloadedOnly":0,"booksNoProgress":37,"booksError":0,"booksUnavailable":0}
 {}2023-07-16 12:16:24.872 -05:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"total":4,"pdfsDownloaded":4,"pdfsNotDownloaded":0,"pdfsUnavailable":0}
 {}2023-07-16 12:16:26.385 -05:00 [INF] (at AudibleApi.Api+<downloadItemPage>d__48.MoveNext()) Page 1: 37 results
 {}2023-07-16 12:16:26.405 -05:00 [INF] (at AudibleUtilities.ApiExtended+<getItemsAsync>d__14.MoveNext()) Completed indexing series episodes after 0 ms.
 {}2023-07-16 12:16:26.421 -05:00 [INF] (at AudibleUtilities.ApiExtended+<getItemsAsync>d__14.MoveNext()) Completed library scan in 1590 ms.
 {}2023-07-16 12:16:26.437 -05:00 [INF] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__15.MoveNext()) GetAllLibraryItems: Total count 37
 {}2023-07-16 12:16:26.449 -05:00 [INF] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__15.MoveNext()) Begin long-running import
 {}2023-07-16 12:16:26.571 -05:00 [INF] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__15.MoveNext()) Import complete. New count 0
 {}2023-07-16 12:18:04.608 -05:00 [INF] (at AppScaffolding.LibationScaffolding.logStartupState(LibationFileManager.Configuration)) 

 {}2023-07-16 12:18:04.646 -05:00 [INF] (at AppScaffolding.LibationScaffolding.logStartupState(LibationFileManager.Configuration)) Begin. {"AppName":"Libation","Version":"10.6.2.1","ReleaseIdentifier":"WindowsAvalonia","OS":"Windows","InteropFunctionsType":"WindowsConfigApp.WinInterop","Mode":"Release","LogLevel_Verbose_Enabled":false,"LogLevel_Debug_Enabled":false,"LogLevel_Information_Enabled":true,"LogLevel_Warning_Enabled":true,"LogLevel_Error_Enabled":true,"LogLevel_Fatal_Enabled":true,"BetaOptIn":false,"UseCoverAsFolderIcon":true,"LibationFiles":"C:\\Users\\CLHat\\Libation","BooksDirectory":"\\\\?\\C:\\Users\\CLHat\\Documents\\Libation\\Books","InProgress":"C:\\Users\\CLHat\\AppData\\Local\\Temp\\Libation","DownloadsInProgressDirectory":"\\\\?\\C:\\Users\\CLHat\\AppData\\Local\\Temp\\Libation\\DownloadsInProgress","DownloadsInProgressFiles":0,"DecryptInProgressDirectory":"\\\\?\\C:\\Users\\CLHat\\AppData\\Local\\Temp\\Libation\\DecryptInProgress","DecryptInProgressFiles":0}
 {}2023-07-16 12:18:04.762 -05:00 [ERR] (at LibationFileManager.InteropFactory.CurrentDomain_AssemblyResolve(System.Object, System.ResolveEventArgs)) Unable to load module Windows, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime
 {}2023-07-16 12:18:04.780 -05:00 [ERR] (at LibationFileManager.InteropFactory.CurrentDomain_AssemblyResolve(System.Object, System.ResolveEventArgs)) Unable to load module Microsoft.Windows.SDK.NET, Culture=neutral, PublicKeyToken=null
 {}2023-07-16 12:18:05.352 -05:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"total":37,"booksFullyBackedUp":0,"booksDownloadedOnly":0,"booksNoProgress":37,"booksError":0,"booksUnavailable":0}
 {}2023-07-16 12:18:05.374 -05:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"total":4,"pdfsDownloaded":4,"pdfsNotDownloaded":0,"pdfsUnavailable":0}
 {}2023-07-16 12:18:05.745 -05:00 [INF] (at AudibleUtilities.ApiExtended+<CreateAsync>d__7.MoveNext()) {"LoginType":"ILoginChoiceEager","Account":"AccountId=C[...]h@g[...]l.c[...]m|AccountName=C[...]s|Locale=us","LocaleName":"us"}
 {}2023-07-16 12:18:05.787 -05:00 [INF] (at ApplicationServices.LibraryCommands+<scanAccountAsync>d__18.MoveNext()) ImportLibraryAsync. {"Account":"AccountId=C[...]h@g[...]l.c[...]m|AccountName=C[...]s|Locale=us"}
 {}2023-07-16 12:18:05.848 -05:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"total":37,"booksFullyBackedUp":0,"booksDownloadedOnly":0,"booksNoProgress":37,"booksError":0,"booksUnavailable":0}
 {}2023-07-16 12:18:05.862 -05:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"total":4,"pdfsDownloaded":4,"pdfsNotDownloaded":0,"pdfsUnavailable":0}
 {}2023-07-16 12:18:07.029 -05:00 [INF] (at AudibleApi.Api+<downloadItemPage>d__48.MoveNext()) Page 1: 37 results
 {}2023-07-16 12:18:07.046 -05:00 [INF] (at AudibleUtilities.ApiExtended+<getItemsAsync>d__14.MoveNext()) Completed indexing series episodes after 0 ms.
 {}2023-07-16 12:18:07.057 -05:00 [INF] (at AudibleUtilities.ApiExtended+<getItemsAsync>d__14.MoveNext()) Completed library scan in 1242 ms.
 {}2023-07-16 12:18:07.073 -05:00 [INF] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__15.MoveNext()) GetAllLibraryItems: Total count 37
 {}2023-07-16 12:18:07.086 -05:00 [INF] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__15.MoveNext()) Begin long-running import
 {}2023-07-16 12:18:07.207 -05:00 [INF] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__15.MoveNext()) Import complete. New count 0
 {}2023-07-16 12:23:05.840 -05:00 [INF] (at AudibleUtilities.ApiExtended+<CreateAsync>d__7.MoveNext()) {"LoginType":"ILoginChoiceEager","Account":"AccountId=C[...]h@g[...]l.c[...]m|AccountName=C[...]s|Locale=us","LocaleName":"us"}
 {}2023-07-16 12:23:05.858 -05:00 [INF] (at ApplicationServices.LibraryCommands+<scanAccountAsync>d__18.MoveNext()) ImportLibraryAsync. {"Account":"AccountId=C[...]h@g[...]l.c[...]m|AccountName=C[...]s|Locale=us"}
 {}2023-07-16 12:23:06.928 -05:00 [INF] (at AudibleApi.Api+<downloadItemPage>d__48.MoveNext()) Page 1: 37 results
 {}2023-07-16 12:23:06.944 -05:00 [INF] (at AudibleUtilities.ApiExtended+<getItemsAsync>d__14.MoveNext()) Completed indexing series episodes after 0 ms.
 {}2023-07-16 12:23:06.953 -05:00 [INF] (at AudibleUtilities.ApiExtended+<getItemsAsync>d__14.MoveNext()) Completed library scan in 1075 ms.
 {}2023-07-16 12:23:06.964 -05:00 [INF] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__15.MoveNext()) GetAllLibraryItems: Total count 37
 {}2023-07-16 12:23:06.976 -05:00 [INF] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__15.MoveNext()) Begin long-running import
 {}2023-07-16 12:23:07.047 -05:00 [INF] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__15.MoveNext()) Import complete. New count 0
 {}

### PR DESCRIPTION
**Pull request by Mbucari**
I'm marking this as draft because I'm still not sure about some of the choices I made and I want your feedback.

The main event here is added support for full arbitrary-depth category trees and multiple categories per book.

Removed `Book.Category` and added `Book.CategoriesLink`, which is a HashSet of `BookCategory`

`BookCategory` links a `Book` to a `CategoryLadder`.
`CategoryLadder.Categories` is a list of `Category`, representing the ladder. `CategoryLadder.Categories` is in a many-to-many relationship with `Category.CategoryLadders`

I replaced `CategoriesNames()` extension method with `LowestCategoryNames()` which returns an array of the lowest rungs of the ladders. Everywhere which used to display "Parent > Child" now displays "Genre1, Genre2"

### CODE REVIEW

File: Source/LibationSearchEngine/SearchEngine.cs [hunk 1]
```diff
@@ -41,7 +41,7 @@ private static bool isAuthorNarrated(Book book)
             { FieldType.String, lb => lb.Book.Publisher, nameof(Book.Publisher) },
             { FieldType.String, lb => lb.Book.SeriesNames(), "SeriesNames", "Narrator", "Series" },
             { FieldType.String, lb => string.Join(", ", lb.Book.SeriesLink.Select(s => s.Series.AudibleSeriesId)), "SeriesId" },
-            { FieldType.String, lb => lb.Book.CategoriesIds() is null ? null : string.Join(", ", lb.Book.CategoriesIds()), nameof(Book.Category), "Categories", "CategoriesId", "CategoryId", "CategoriesNames" },
+            { FieldType.String, lb => lb.Book.CategoriesIds() is null ? null : string.Join(", ", lb.Book.CategoriesIds()), "Category", "Categories", "CategoriesId", "CategoryId", "CategoriesNames" },
```
Comment (Mbucari) [inline Source/LibationSearchEngine/SearchEngine.cs:44]: Also, I think this is a bug. All "category" fields relate only to the category ID, and none reference the category names.

It's been this way since before my refactor:
https://github.com/rmcrackan/Libation/blob/e62f01d2a39e02dd77d8f54fb15742878666e282/Source/LibationSearchEngine/SearchEngine.cs#L65-L69

**Comment by rmcrackan** [comment]
> I think this is a bug

Yup!

**Comment by rmcrackan** [comment]
That's a lot of churn. At first browse, this all looks reasonable. It looks like it covers cases without categories. Upgrades/migrations look like they'll get updated on the next scan. Upserting on the book does a full replace so it's no problem if audible completely recategorizes the book. I assume audible having this field as null isn't a thing or your testing would have seen that EnsureNotNull validator get hit.

File: Source/DtoImporterService/BookImporter.cs [hunk 2]
```diff
@@ -201,6 +185,17 @@ private void updateBook(ImportItem importItem, Book book)
...
+
+			if (item.CategoryLadders is not null)
+			{
+				foreach (var ladder in item.CategoryLadders.Select(cl => cl.Ladder).Where(l => l?.Length > 0))
+				{
+					var categoryIds = ladder.Select(l => l.CategoryId).ToList();
+					var cata = categoryImporter.LadderCache.Single(c => c.Equals(categoryIds));
+
+					book.UpsertCategories(cata);
+				}
```
Comment (Mbucari) [inline Source/DtoImporterService/BookImporter.cs:197]: >  I assume audible having this field as null isn't a thing or your testing would have seen that EnsureNotNull validator get hit.

I take care of that here, and there's an identical check CategoryImporter

**Comment by Mbucari** [comment]
> Upgrades/migrations look like they'll get updated on the next scan.

Yup. After upgrading the Category column is blank, and then after the first scan it gets repopulated.

> Upserting on the book does a full replace so it's no problem if audible completely recategorizes the book.

It doesn't. It'll add or update, but it won't remove preexisting BookCategories that weren't present in the Library scan. In this way it's identical to series upsert, but I think you're right it should just rewrite the whole CategoriesLink on update.

File: Source/DtoImporterService/CategoryImporter.cs [hunk 3]
```diff
@@ -65,6 +65,8 @@ private int upsertCategories(List<Ladder[]> ladders)
 					var id = ladder[i].CategoryId;
 					var name = ladder[i].CategoryName;
 
+					if (name == "Storia") ;
```
Comment (rmcrackan) [inline Source/DtoImporterService/CategoryImporter.cs:68]: Aside from the fact that I don't know what "Storia" is, this looks like an unintentional way to declare an empty statement.

Comment (Mbucari) [reply Source/DtoImporterService/CategoryImporter.cs:68]: Sorry, I pushed these to save my work remotely while I fugue out what the hell is going on here. I'm going to clean it up before I ask for a review.

It turns out that trying to modify Book.CategoryLink starts another tracking instance, so the context can't be saved. I _thin_ it has to do with EF's automatic configuration of the many-to-many, but really I'm just fumbling around here trying to sort this out.

**Comment by rmcrackan** [comment]
Sorry for jumping the gun. I'll leave ya alone

File: Source/DataLayer/EfClasses/Book.cs [hunk 4]
```diff
@@ -144,47 +131,70 @@ private void replaceContributors(IEnumerable<Contributor> newContributors, Role
...
+                    _categoriesReadOnly = CategoriesLink.ToList().AsReadOnly();
+                return _categoriesReadOnly;
+            }
+        }
+		public void SetCategoryLadders(IEnumerable<CategoryLadder> ladders)
+		{
+			ArgumentValidator.EnsureNotNull(ladders, nameof(ladders));
+
+			//Replace all existing category ladders.
+            //Some books make have duplocate ladders
```
Comment (Mbucari) [inline Source/DataLayer/EfClasses/Book.cs:190]: This little tidbit right here cost hours.

**Comment by Mbucari** [comment]
@rmcrackan I'm ready.

[Add category ladders](https://github.com/rmcrackan/Libation/pull/682/commits/ea6adeb58f666d209c2e8dabd0656857871a030e) is unchanged from last night. My fixing and tweaking is all in [Improved Category Ladders](https://github.com/rmcrackan/Libation/pull/682/commits/3211b2dc853b8aafb3fde488eb632fde7e8cd9a1).

Fixed the search bug I mentioned last night ([Fix category search indexing](https://github.com/rmcrackan/Libation/pull/682/commits/4e34834c357711cd9a7bb903aa406ce4f07967a4))

[Fix grid update bug](https://github.com/rmcrackan/Libation/pull/682/commits/b94f9bbc152c611f4cfbfa8a677616f7d5579991)
This bug has been present in classic for a long time, but I only noticed it while working on the new categories.

[Improve GridView](https://github.com/rmcrackan/Libation/pull/682/commits/914e574bf8f1a5421ef4045df3401a452055aca2)
- Remove LongDescription. 
- Description has the full description. Let me know if you have a problem with this.  Given that users can resize their columns, I don't see a reason to truncate it.
- Better MyRating updating

File: Source/DataLayer/EntityExtensions.cs [hunk 5]
```diff
@@ -7,8 +7,13 @@
 namespace DataLayer
 {
     public static class EntityExtensions
-    {
-        public static string TitleSortable(this Book book) => Formatters.GetSortName(book.Title + book.Subtitle);
+	{
+		public static IEnumerable<BookContributor> ByRole(this IEnumerable<BookContributor> contributors, Role role)
```
Comment (rmcrackan) [inline Source/DataLayer/EntityExtensions.cs:11]: I love stuff like this. so much more expressive.

**Comment by rmcrackan** [comment]
In the comments for #677 you mentioned that fix would be in the next release. I didn't see it here. Did I miss it? Or did it not make the cut?

File: Source/DataLayer/EfClasses/Book.cs (hunk 4 above)
Comment (rmcrackan) [reply Source/DataLayer/EfClasses/Book.cs:190]: Oof, that sounds like a fun edge case to debug

**Comment by Mbucari** [comment]
> In the comments for #677 you mentioned that fix would be in the next release. I didn't see it here. Did I miss it? Or did it not make the cut?

https://github.com/rmcrackan/Libation/pull/679

It was in this pr, but I mistakenly typed it out as 667 instead of 677.

**Comment by rmcrackan** [comment]
Cool. Thanks.
